default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/shutter-network/pre-commit-go-hooks
    rev: "ed735ca2048f831625cd155cf6a38b4a42d79d9b"
    hooks:
      - id: go-mod-tidy
        name: Run go mod tidy in shuttermint
        args: ["./shuttermint"]
      - id: go-mod-tidy
        name: Run go mod tidy in shlib
        args: ["./shlib"]
      - id: gci
        args:
          [
            "--custom-order",
            "-sStandard",
            "-sDefault",
            "-sPrefix(github.com/shutter-network/shutter)",
          ]
        exclude: |
          (?x)(
              ^shuttermint/contract/binding\.go$|
              ^shuttermint/shmsg/.*\.pb\.go$|
              ^shuttermint/shcryptowasm/.*_wasm\.go$
          )
      - id: gofumpt
        exclude: |
          (?x)(
              ^shuttermint/contract/binding\.go$|
              ^shuttermint/shmsg/.*\.pb\.go$|
              ^shuttermint/shcryptowasm/.*_wasm\.go$
          )

  # CircleCI stop here

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        additional_dependencies:
          ["prettier@2.3.1", "prettier-plugin-solidity@1.0.0-beta.13"]
        args: ["--plugin=prettier-plugin-solidity"]
        exclude: "^contracts/openzeppelin/.*"

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/sqlalchemyorg/zimports
    rev: 38c16831e6ee709aa9b4395b9b1efb6ed4d6ad8c
    hooks:
      - id: zimports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        entry: tools/pre-commit-wrapper.py mypy
        additional_dependencies: ["pip-tools==6.2.0"]
        files: "^(contracts/tests/.*|noxfile.py)$"
