version: 2.1

# CircleCI dynamic configuration file, see
# https://circleci.com/docs/2.0/dynamic-config/

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.3

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            contracts/.* contracts-changed true
            shuttermint/.* shuttermint-changed true
            shlib/.* shuttermint-changed true
          base-revision: main
          config-path: .circleci/continue_config.yml
