jobs:
  test-contracts:
    executor: py37
    working_directory: ~/shutter
    steps:
      - checkout
      - install-nox
      - restore_cache:
          keys:
            - test-contracts-v4-{{ checksum "~/fingerprint_python.txt" }}-{{ checksum "requirements.txt" }}-{{ checksum "contracts/brownie-config.yaml" }}
      - run:
          name: "Run tests"
          command: |
            nox -s test_contracts
      - save_cache:
          key: test-contracts-v4-{{ checksum "~/fingerprint_python.txt" }}-{{ checksum "requirements.txt" }}-{{ checksum "contracts/brownie-config.yaml" }}
          paths:
            - ~/shutter/.nox
            - ~/shutter/.mypy_cache
            - ~/shutter/.brownie
            - ~/.solcx
  mypy:
    executor: py37
    working_directory: ~/shutter
    steps:
      - checkout
      - install-nox
      - restore_cache:
          key: mypy-v1-{{ checksum "~/fingerprint_python.txt" }}-{{ checksum "requirements.txt" }}
      - run:
          name: "Run mypy with nox"
          command: |
            nox -s mypy
      - save_cache:
          key: mypy-v1-{{ checksum "~/fingerprint_python.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/shutter/.nox

workflows:
  contracts:
    jobs:
      - test-contracts
      - mint-abigen
      - mypy
